# Generated by Django 3.2.7 on 2021-10-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
