# Generated by Django 3.2.7 on 2021-10-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_biodata_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='foto',
        ),
    ]
