# Generated by Django 3.2.7 on 2021-11-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_remove_biodata_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='nama',
            field=models.CharField(max_length=20),
        ),
    ]
